# Y: extra ports
# - "6001:5000" # Expose port 5000 inside container → 6001 on host
# - "6002:5000" # Expose port 5000 inside container → 6001 on host
# - "7341:5000" # Expose port 5000 inside container → 6001 on host

version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/lazycontacts?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-prod
      NODE_ENV: development
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
